name: flutter_pitel_voip
description: flutter_pitel_voip is package support for voice-over-IP (VoIP) call. Support VoIP call between 2 extension or outgoing call mobile phone number.
version: 1.0.11+1
homepage: https://github.com/tel4vn/flutter-pitel-voip
repository: https://github.com/tel4vn/flutter-pitel-voip
issue_tracker: https://github.com/tel4vn/flutter-pitel-voip/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3

  crypto: ^3.0.0
  flutter_webrtc: ^0.14.1
  intl: ">=0.19.0 <0.21.0"
  logger: ^2.6.2
  parser_error: ^0.2.0
  path: ^1.6.4
  random_string: ^2.0.0
  recase: ^4.0.0
  sdp_transform: ^0.3.2
  uuid: ^4.5.1
  dartz: ^0.10.1
  flutter_callkit_incoming_timer: ^1.0.3+13
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  device_info_plus: ^11.4.0
  wakelock_plus: ^1.3.2
  shared_preferences: ^2.5.3
  eraser: ^3.0.0
  throttling: ^2.0.1
  connectivity_plus: ^6.1.4
  flutter_easyloading: ^3.0.5
  network_info_plus: ^6.1.4
  flutter_show_when_locked: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.pitel.flutter_pitel_voip
        pluginClass: PluginPitelPlugin
      ios:
        pluginClass: PluginPitelPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
